# SPL

## Doolitle

In [2]:
def luDecomposition(mat, n):
 
    lower = [[0 for x in range(n)]
             for y in range(n)]
    upper = [[0 for x in range(n)]
             for y in range(n)]
    
    # Dekomposisi Matriks LU (Bawah dan Atas)
    for i in range(n):
 
        # Upper (Atas)
        for k in range(i, n):
 
            # Penjumlahan dari L(i, j) * U(j, k)
            sum = 0
            for j in range(i):
                sum += (lower[i][j] * upper[j][k])
 
            # Mengevaluasi U(i, k)
            upper[i][k] = float(mat[i][k] - sum)
 
        # Lower (Bawah)
        for k in range(i, n):
            if (i == k):
                lower[i][i] = 1  # Diagonal = 1
            else:
 
                # Penjumlahan of L(k, j) * U(j, i)
                sum = 0
                for j in range(i):
                    sum += (lower[k][j] * upper[j][i])
 
                # Mengevaluasi L(k, i)
                lower[k][i] = float((mat[k][i] - sum) /
                                  upper[i][i])
     
    print("Lower\t\t\t\tUpper")
 
    # Hasil :
    for i in range(n):
        
        # Lower
        for j in range(n):
            print("%.2f" %  lower[i][j], end="\t")
        print("", end="\t")
 
        # Upper
        for j in range(n):
            print("%.2f" %  upper[i][j], end="\t")
        print("")

#"%.2f" %        
 
# Matriks
#mat = [[2, -1, -2],
#       [-4, 6, 3],
#       [-4, -2, 8]]


#mat = [[1, -1, 2,-1],
#       [1, 1, 1,0],
#       [2, -2, 3,-3],
#       [1,-1,4,3]]

mat = [[1, 2, 3],
       [3, -1, 2],
       [4, -6, -4]]


#mat = [[4, 1, 2],
#       [3, 3, 1],
#       [2, 1, 3]]
       
#mat = [[4, 3, 2] , [1, 3, 1], [2, 1, 3]]

luDecomposition(mat, 3) 
#luDecomposition(mat, 4)

Lower				Upper
1.00	0.00	0.00		1.00	2.00	3.00	
3.00	1.00	0.00		0.00	-7.00	-7.00	
4.00	2.00	1.00		0.00	0.00	-2.00	


## Gauss-Seidel

In [3]:
# Gauss Seidel 

f1 = lambda a, b, c, d, e: (5 + 2 * b + c) / 8
f2 = lambda a, b, c, d, e: (2 + 2 * a + 4 * c + d) / 9
f3 = lambda a, b, c, d, e: (a + 3 * b + d + 2 * e) / 7
f4 = lambda a, b, c, d, e: (1 + 4 * b + 2 * c + 5 * e) / 12
f5 = lambda a, b, c, d, e: (5 + 7 * c + 3 * d) / 15

a0 = 0
b0 = 0
c0 = 0
d0 = 0
e0 = 0

count = 1

# Galat 
eps = 0.0001

print('\nHitung\ta\tb\tc\td\te\n')

condition = True

while condition:
    a1 = f1(a0, b0, c0, d0, e0)
    b1 = f2(a1, b0, c0, d0, e0)
    c1 = f3(a1, b1, c0, d0, e0)
    d1 = f4(a1, b1, c1, d0, e0)
    e1 = f4(a1, b1, c1, d1, e0)

    print('%d\t%0.4f\t%0.4f\t%0.4f\t%0.4f\t%0.4f\n' % (count, a1, b1, c1, d1, e1))
    ep1 = abs(a0 - a1)
    ep2 = abs(b0 - b1)
    ep3 = abs(c0 - c1)
    ep4 = abs(d0 - d1)
    ep5 = abs(e0 - e1)

    count += 1
    a0 = a1
    b0 = b1
    c0 = c1
    d0 = d1
    e0 = e1

    condition = ep1 > eps and ep2 > eps and ep3 > eps and ep4 > eps and ep5 > eps

print('\nSolusi: a=%0.4f, b=%0.4f, c=%0.4f, d=%0.4f and eps = %0.4f\n' % (a1, b1, c1, d1, e1))


Hitung	a	b	c	d	e

1	0.6250	0.3611	0.2440	0.2444	0.2444

2	0.7458	0.5236	0.4357	0.4323	0.4323

3	0.8104	0.6440	0.5770	0.5743	0.5743

4	0.8581	0.7332	0.6829	0.6808	0.6808

5	0.8937	0.8000	0.7623	0.7607	0.7607

6	0.9203	0.8501	0.8218	0.8206	0.8206

7	0.9402	0.8876	0.8664	0.8655	0.8655

8	0.9552	0.9157	0.8999	0.8992	0.8992

9	0.9664	0.9368	0.9249	0.9244	0.9244

10	0.9748	0.9526	0.9437	0.9433	0.9433

11	0.9811	0.9645	0.9578	0.9575	0.9575

12	0.9858	0.9734	0.9684	0.9682	0.9682

13	0.9894	0.9800	0.9763	0.9761	0.9761

14	0.9920	0.9850	0.9822	0.9821	0.9821

15	0.9940	0.9888	0.9867	0.9866	0.9866

16	0.9955	0.9916	0.9900	0.9899	0.9899

17	0.9966	0.9937	0.9925	0.9925	0.9925

18	0.9975	0.9953	0.9944	0.9943	0.9943

19	0.9981	0.9965	0.9958	0.9958	0.9958

20	0.9986	0.9973	0.9968	0.9968	0.9968

21	0.9989	0.9980	0.9976	0.9976	0.9976

22	0.9992	0.9985	0.9982	0.9982	0.9982

23	0.9994	0.9989	0.9987	0.9987	0.9987

24	0.9996	0.9992	0.9990	0.9990	0.9990

25	0.9997	0.9994	0.9993	0.9992	0.9992

26	0.9997	0.999

## Crout

In [4]:
import numpy as np

def showMatrix(matrix):
    n = len(matrix)
    for i in range (n):
        for j in range(n):
            print('%.2f' % matrix[i][j], end='\t')
        print("")

A = np.array([[1,2,1],[-2,3,5],[6,2,-1]],dtype=float)
print("Matriks A: ",); showMatrix(A)

U = np.copy(A)
print("\nMatriks UA: ",); showMatrix(U)

U[1,:] += 2 * U[0,:]
print("U: "); showMatrix(U)

E1 = np.identity(3)

Matriks A: 
1.00	2.00	1.00	
-2.00	3.00	5.00	
6.00	2.00	-1.00	

Matriks UA: 
1.00	2.00	1.00	
-2.00	3.00	5.00	
6.00	2.00	-1.00	
U: 
1.00	2.00	1.00	
0.00	7.00	7.00	
6.00	2.00	-1.00	


In [5]:
import numpy as np

def crout(A):
    L = np.zeros((3, 3))
    U = np.zeros((3, 3))
    
    for k in range(0, 3):
        U[k, k] = 1 

        for j in range(k, 3):
            sum0 = sum([L[j, s] * U[s, k] for s in range(0, j)]) #range from index 0
            L[j, k] = A[j, k] - sum0 #reversed index
            print(f"{j}. ",L)
            print("")

        for j in range(k+1, 3):
            sum1 = sum([L[k, s] * U[s, j] for s in range(0, k)]) #range from index 0
            U[k, j] = (A[k, j] - sum1) / L[k, k]
            print(f"{j}. ",U)
            print("")
    print(L)
    print(U)
    return L, U

A = np.array([[60.0, 30.0, 20.0], [30.0, 20.0, 15.0], [20.0, 15.0, 12.0]])
print(f"Matriks A: \n{A}")
print("\nCrout: "); crout(A)

Matriks A: 
[[60. 30. 20.]
 [30. 20. 15.]
 [20. 15. 12.]]

Crout: 
0.  [[60.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]

1.  [[60.  0.  0.]
 [30.  0.  0.]
 [ 0.  0.  0.]]

2.  [[60.  0.  0.]
 [30.  0.  0.]
 [20.  0.  0.]]

1.  [[1.  0.5 0. ]
 [0.  0.  0. ]
 [0.  0.  0. ]]

2.  [[1.         0.5        0.33333333]
 [0.         0.         0.        ]
 [0.         0.         0.        ]]

1.  [[60.  0.  0.]
 [30.  5.  0.]
 [20.  0.  0.]]

2.  [[60.  0.  0.]
 [30.  5.  0.]
 [20.  5.  0.]]

2.  [[1.         0.5        0.33333333]
 [0.         1.         1.        ]
 [0.         0.         0.        ]]

2.  [[60.          0.          0.        ]
 [30.          5.          0.        ]
 [20.          5.          0.33333333]]

[[60.          0.          0.        ]
 [30.          5.          0.        ]
 [20.          5.          0.33333333]]
[[1.         0.5        0.33333333]
 [0.         1.         1.        ]
 [0.         0.         1.        ]]


(array([[60.        ,  0.        ,  0.        ],
        [30.        ,  5.        ,  0.        ],
        [20.        ,  5.        ,  0.33333333]]),
 array([[1.        , 0.5       , 0.33333333],
        [0.        , 1.        , 1.        ],
        [0.        , 0.        , 1.        ]]))